language: php

sudo: false

php:
  - 7.3
  - 7.4

env:
  matrix:
    - LARAVEL=^7.0
    - LARAVEL=^8.0

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
